library verilog;
use verilog.vl_types.all;
entity getCtrl is
    generic(
        s0              : integer := 0;
        s1              : integer := 1;
        s2              : integer := 2;
        s3              : integer := 3;
        s4              : integer := 4;
        s5              : integer := 5;
        s6              : integer := 6;
        s7              : integer := 7;
        s8              : integer := 8;
        s9              : integer := 9;
        s10             : integer := 10;
        s11             : integer := 11;
        s12             : integer := 12;
        s13             : integer := 13;
        s14             : integer := 14;
        s15             : integer := 15;
        s16             : integer := 16;
        s17             : integer := 17;
        s18             : integer := 18;
        s19             : integer := 19;
        s20             : integer := 20;
        s21             : integer := 21
    );
    port(
        state           : in     vl_logic_vector(4 downto 0);
        zero            : in     vl_logic;
        overflow        : in     vl_logic;
        IRWr            : out    vl_logic;
        PCWr            : out    vl_logic;
        GPRDst          : out    vl_logic_vector(1 downto 0);
        ALUSrc          : out    vl_logic;
        Mem2Reg         : out    vl_logic_vector(1 downto 0);
        GPRWr           : out    vl_logic;
        MemWr           : out    vl_logic_vector(1 downto 0);
        nPC_sel         : out    vl_logic;
        ExtOp           : out    vl_logic_vector(1 downto 0);
        ALUOp           : out    vl_logic_vector(2 downto 0);
        j               : out    vl_logic;
        jr              : out    vl_logic;
        ByteSrc         : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of s0 : constant is 1;
    attribute mti_svvh_generic_type of s1 : constant is 1;
    attribute mti_svvh_generic_type of s2 : constant is 1;
    attribute mti_svvh_generic_type of s3 : constant is 1;
    attribute mti_svvh_generic_type of s4 : constant is 1;
    attribute mti_svvh_generic_type of s5 : constant is 1;
    attribute mti_svvh_generic_type of s6 : constant is 1;
    attribute mti_svvh_generic_type of s7 : constant is 1;
    attribute mti_svvh_generic_type of s8 : constant is 1;
    attribute mti_svvh_generic_type of s9 : constant is 1;
    attribute mti_svvh_generic_type of s10 : constant is 1;
    attribute mti_svvh_generic_type of s11 : constant is 1;
    attribute mti_svvh_generic_type of s12 : constant is 1;
    attribute mti_svvh_generic_type of s13 : constant is 1;
    attribute mti_svvh_generic_type of s14 : constant is 1;
    attribute mti_svvh_generic_type of s15 : constant is 1;
    attribute mti_svvh_generic_type of s16 : constant is 1;
    attribute mti_svvh_generic_type of s17 : constant is 1;
    attribute mti_svvh_generic_type of s18 : constant is 1;
    attribute mti_svvh_generic_type of s19 : constant is 1;
    attribute mti_svvh_generic_type of s20 : constant is 1;
    attribute mti_svvh_generic_type of s21 : constant is 1;
end getCtrl;
